### ISSUE TITLE
Problem with page selection

### ISSUE THREAD

**Issue by Next-rus** [Sajaki/RecentTopics#65] opened 2017-09-19 21:23 UTC
phpbb 3.2.1
recenttopics 2.2.3

I have a problem with page selection.
For example. I had chosen 3rd page (in address bar: /index.php?recent_topics_start=10), but displayed 2nd page. When I had chosen 4th page (in address bar: /index.php?recent_topics_start=15), then displayed 3rd page. Etc.

**Comment by Galixte** [comment] 2017-09-20 03:39
Duplicate of: https://github.com/Sajaki/RecentTopics/commit/52867dc9dbfc45ee07eb2c2cbe11eb32d3be102d#commitcomment-24421935

**Comment by avandenberghe** [comment] 2017-09-21 08:48
solved in 2.2.4

**Closed as completed by avandenberghe** 2017-09-21 08:48 UTC
